kind: BuildConfig
apiVersion: build.openshift.io/v1
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'om-top10-oum:latest'
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 1Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: docker/Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/pablo-flores/python.git'
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: om-top10-oum-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: om-top10-oum-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 2
